/**
 * Seed de Egresos para MongoDB
 * Equivalente al seeder 20260118000004-demo-egresos.js de PostgreSQL
 */

// Esta función recibe los IDs de los perfiles creados dinámicamente
const getEgresosSeedData = (perfilIds) => {
  // perfilIds es un objeto con: { adminPerfil, mariaPersonal, mariaNegocio, carlosPersonal }
  return [
    // Egresos del perfil Personal de María
    {
      perfilId: perfilIds.mariaPersonal,
      monto: 300.0,
      descripcion: "Alquiler",
      categoria: "Vivienda",
      frecuencia: "mensual",
      diaMes: 1,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-01"),
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-02-15"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      monto: 150.0,
      descripcion: "Supermercado",
      categoria: "Alimentación",
      frecuencia: "semanal",
      diasSemana: [1],
      notificacionActiva: false,
      activo: true,
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-02-15"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      monto: 80.0,
      descripcion: "Luz y Agua",
      categoria: "Servicios",
      frecuencia: "mensual",
      diaMes: 10,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-10"),
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-02-15"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      monto: 30.0,
      descripcion: "Internet",
      categoria: "Servicios",
      frecuencia: "mensual",
      diaMes: 5,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-05"),
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-02-15"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      monto: 50.0,
      descripcion: "Cena con amigos",
      categoria: "Entretenimiento",
      frecuencia: "ocasional",
      fechaEspecifica: new Date("2026-01-15"),
      activo: false,
      clasificacionIA: "Restaurante - Comida italiana",
      createdAt: new Date("2024-02-20"),
      updatedAt: new Date("2024-02-20"),
    },
    // Egresos del perfil Negocio de María
    {
      perfilId: perfilIds.mariaNegocio,
      monto: 500.0,
      descripcion: "Inventario",
      categoria: "Otros",
      frecuencia: "mensual",
      diaMes: 15,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-15"),
      createdAt: new Date("2024-02-20"),
      updatedAt: new Date("2024-02-20"),
    },
    {
      perfilId: perfilIds.mariaNegocio,
      monto: 200.0,
      descripcion: "Local Comercial",
      categoria: "Vivienda",
      frecuencia: "mensual",
      diaMes: 1,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-01"),
      createdAt: new Date("2024-02-20"),
      updatedAt: new Date("2024-02-20"),
    },
    // Egresos de Carlos
    {
      perfilId: perfilIds.carlosPersonal,
      monto: 3000.0,
      descripcion: "Renta Departamento",
      categoria: "Vivienda",
      frecuencia: "mensual",
      diaMes: 1,
      notificacionActiva: true,
      activo: true,
      proximaEjecucion: new Date("2026-02-01"),
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-01"),
    },
    {
      perfilId: perfilIds.carlosPersonal,
      monto: 2000.0,
      descripcion: "Supermercado Semanal",
      categoria: "Alimentación",
      frecuencia: "semanal",
      diasSemana: [6],
      notificacionActiva: false,
      activo: true,
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-01"),
    },
    {
      perfilId: perfilIds.carlosPersonal,
      monto: 1500.0,
      descripcion: "Gasolina",
      categoria: "Transporte",
      frecuencia: "semanal",
      diasSemana: [0, 3],
      notificacionActiva: false,
      activo: true,
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-01"),
    },
  ];
};

module.exports = { getEgresosSeedData };
