/**
 * Seed de Historial para MongoDB
 * Registros de transacciones históricas
 */

const getHistorialSeedData = (perfilIds) => {
  return [
    // ========================================
    // Historial para perfil Personal de María
    // ========================================
    
    // Enero 2024
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario mensual Enero",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-01-15"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 150.0,
      descripcion: "Compra supermercado",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2024-01-18"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Pago alquiler",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2024-01-05"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 200.0,
      descripcion: "Freelance diseño web",
      categoria: "Freelance",
      fechaEjecucion: new Date("2024-01-22"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 45.0,
      descripcion: "Luz y agua",
      categoria: "Servicios",
      fechaEjecucion: new Date("2024-01-10"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 30.0,
      descripcion: "Internet fibra",
      categoria: "Servicios",
      fechaEjecucion: new Date("2024-01-08"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 85.0,
      descripcion: "Cena con amigas",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2024-01-20"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 120.0,
      descripcion: "Ropa nueva",
      categoria: "Compras",
      fechaEjecucion: new Date("2024-01-28"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 65.0,
      descripcion: "Farmacia y medicinas",
      categoria: "Salud",
      fechaEjecucion: new Date("2024-01-12"),
      mes: 1,
      anio: 2024,
    },
    
    // Febrero 2024
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario mensual Febrero",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-02-15"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 350.0,
      descripcion: "Proyecto freelance sitio corporativo",
      categoria: "Freelance",
      fechaEjecucion: new Date("2024-02-10"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Febrero",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2024-02-05"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 180.0,
      descripcion: "Supermercado semanal",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2024-02-18"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 95.0,
      descripcion: "Cine y restaurante",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2024-02-14"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 40.0,
      descripcion: "Gasolina",
      categoria: "Transporte",
      fechaEjecucion: new Date("2024-02-22"),
      mes: 2,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 150.0,
      descripcion: "Gimnasio trimestral",
      categoria: "Salud",
      fechaEjecucion: new Date("2024-02-01"),
      mes: 2,
      anio: 2024,
    },
    
    // Marzo 2024
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario mensual Marzo",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-03-15"),
      mes: 3,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Marzo",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2024-03-05"),
      mes: 3,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 220.0,
      descripcion: "Compras del mes",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2024-03-12"),
      mes: 3,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 75.0,
      descripcion: "Salón de belleza",
      categoria: "Cuidado Personal",
      fechaEjecucion: new Date("2024-03-20"),
      mes: 3,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 280.0,
      descripcion: "Consultoría diseño UX",
      categoria: "Freelance",
      fechaEjecucion: new Date("2024-03-25"),
      mes: 3,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 55.0,
      descripcion: "Cumpleaños amiga (regalo)",
      categoria: "Regalos",
      fechaEjecucion: new Date("2024-03-18"),
      mes: 3,
      anio: 2024,
    },
    
    // Abril 2024
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario mensual Abril",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-04-15"),
      mes: 4,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Abril",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2024-04-05"),
      mes: 4,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 165.0,
      descripcion: "Mercado mensual",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2024-04-10"),
      mes: 4,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 320.0,
      descripcion: "Reparación auto",
      categoria: "Transporte",
      fechaEjecucion: new Date("2024-04-22"),
      mes: 4,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 450.0,
      descripcion: "Proyecto web e-commerce",
      categoria: "Freelance",
      fechaEjecucion: new Date("2024-04-28"),
      mes: 4,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 90.0,
      descripcion: "Suscripciones digitales",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2024-04-01"),
      mes: 4,
      anio: 2024,
    },
    
    // Mayo 2024
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario mensual Mayo",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-05-15"),
      mes: 5,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Mayo",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2024-05-05"),
      mes: 5,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 195.0,
      descripcion: "Compras supermercado",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2024-05-12"),
      mes: 5,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 250.0,
      descripcion: "Ropa de verano",
      categoria: "Compras",
      fechaEjecucion: new Date("2024-05-20"),
      mes: 5,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 600.0,
      descripcion: "Bono por desempeño",
      categoria: "Bonos",
      fechaEjecucion: new Date("2024-05-30"),
      mes: 5,
      anio: 2024,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 110.0,
      descripcion: "Día de las madres",
      categoria: "Regalos",
      fechaEjecucion: new Date("2024-05-10"),
      mes: 5,
      anio: 2024,
    },
    
    // ========================================
    // Registros de 2025
    // ========================================
    
    // Junio 2025
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario Junio 2025",
      categoria: "Salario",
      fechaEjecucion: new Date("2025-06-15"),
      mes: 6,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Junio",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2025-06-05"),
      mes: 6,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 200.0,
      descripcion: "Compras supermercado",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2025-06-18"),
      mes: 6,
      anio: 2025,
    },
    
    // Septiembre 2025
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario Septiembre 2025",
      categoria: "Salario",
      fechaEjecucion: new Date("2025-09-15"),
      mes: 9,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Septiembre",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2025-09-05"),
      mes: 9,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 180.0,
      descripcion: "Supermercado",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2025-09-20"),
      mes: 9,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 400.0,
      descripcion: "Proyecto freelance",
      categoria: "Freelance",
      fechaEjecucion: new Date("2025-09-28"),
      mes: 9,
      anio: 2025,
    },
    
    // Diciembre 2025
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario Diciembre 2025",
      categoria: "Salario",
      fechaEjecucion: new Date("2025-12-15"),
      mes: 12,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 800.0,
      descripcion: "Bono de Navidad",
      categoria: "Bonos",
      fechaEjecucion: new Date("2025-12-20"),
      mes: 12,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 800.0,
      descripcion: "Alquiler Diciembre",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2025-12-05"),
      mes: 12,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 250.0,
      descripcion: "Regalos de Navidad",
      categoria: "Regalos",
      fechaEjecucion: new Date("2025-12-22"),
      mes: 12,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 300.0,
      descripcion: "Cena de Navidad",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2025-12-24"),
      mes: 12,
      anio: 2025,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 220.0,
      descripcion: "Compras fin de año",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2025-12-30"),
      mes: 12,
      anio: 2025,
    },
    
    // ========================================
    // Registros de 2026 (AÑO ACTUAL)
    // ========================================
    
    // Enero 2026
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 3500.0,
      descripcion: "Salario Enero 2026",
      categoria: "Salario",
      fechaEjecucion: new Date("2026-01-15"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 850.0,
      descripcion: "Alquiler Enero 2026",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2026-01-05"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 180.0,
      descripcion: "Supermercado semanal",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2026-01-10"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 45.0,
      descripcion: "Luz y agua Enero",
      categoria: "Servicios",
      fechaEjecucion: new Date("2026-01-08"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 30.0,
      descripcion: "Internet Enero",
      categoria: "Servicios",
      fechaEjecucion: new Date("2026-01-07"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "ingreso",
      monto: 350.0,
      descripcion: "Freelance landing page",
      categoria: "Freelance",
      fechaEjecucion: new Date("2026-01-25"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 120.0,
      descripcion: "Cena restaurante",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2026-01-20"),
      mes: 1,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 65.0,
      descripcion: "Gasolina",
      categoria: "Transporte",
      fechaEjecucion: new Date("2026-01-28"),
      mes: 1,
      anio: 2026,
    },
    
    // Febrero 2026 (MES ACTUAL)
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 850.0,
      descripcion: "Alquiler Febrero 2026",
      categoria: "Vivienda",
      fechaEjecucion: new Date("2026-02-01"),
      mes: 2,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 95.0,
      descripcion: "Compras supermercado",
      categoria: "Alimentación",
      fechaEjecucion: new Date("2026-02-02"),
      mes: 2,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 45.0,
      descripcion: "Netflix y Spotify",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2026-02-03"),
      mes: 2,
      anio: 2026,
    },
    {
      perfilId: perfilIds.mariaPersonal,
      tipo: "egreso",
      monto: 30.0,
      descripcion: "Internet Febrero",
      categoria: "Servicios",
      fechaEjecucion: new Date("2026-02-04"),
      mes: 2,
      anio: 2026,
    },
    
    // ========================================
    // Historial para perfil Personal de Carlos
    // ========================================
    {
      perfilId: perfilIds.carlosPersonal,
      tipo: "ingreso",
      monto: 2800.0,
      descripcion: "Salario Enero",
      categoria: "Salario",
      fechaEjecucion: new Date("2024-01-30"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.carlosPersonal,
      tipo: "egreso",
      monto: 50.0,
      descripcion: "Netflix y Spotify",
      categoria: "Entretenimiento",
      fechaEjecucion: new Date("2024-01-10"),
      mes: 1,
      anio: 2024,
    },
    {
      perfilId: perfilIds.carlosPersonal,
      tipo: "egreso",
      monto: 300.0,
      descripcion: "Gasolina mensual",
      categoria: "Transporte",
      fechaEjecucion: new Date("2024-01-25"),
      mes: 1,
      anio: 2024,
    },
  ];
};

module.exports = { getHistorialSeedData };
