/**
 * Seed de Planes de Deuda para MongoDB
 * Equivalente al seeder 20260118000007-demo-planes-deuda.js de PostgreSQL
 */

// Esta función recibe los IDs de los perfiles creados dinámicamente
const getPlanesDeudaSeedData = (perfilIds) => {
  // perfilIds es un objeto con: { adminPerfil, mariaPersonal, mariaNegocio, carlosPersonal }
  return [
    // Planes de deuda del perfil Personal de María
    {
      perfilId: perfilIds.mariaPersonal,
      nombre: "Tarjeta Visa",
      descripcion: "Deuda acumulada en tarjeta de crédito",
      categoria: "Tarjeta de Crédito",
      montoDeuda: 1500.0,
      montoPagado: 500.0,
      tasaInteres: 18.5,
      cuotaMensual: 150.0,
      fechaPago: new Date("2026-02-05"),
      estado: "activo",
      prioridad: "alta",
      estrategia: "avalancha",
      acreedor: "Banco Pichincha",
      numeroContrato: "VISA-001234",
      icono: "💳",
      color: "#FF6B6B",
      notificacionActiva: true,
      historialPagos: [
        { fecha: new Date("2024-11-05"), monto: 200, nota: "Pago inicial" },
        { fecha: new Date("2024-12-05"), monto: 150, nota: "Pago mensual" },
        { fecha: new Date("2025-01-05"), monto: 150, nota: "Pago mensual" },
      ],
      createdAt: new Date("2024-11-01"),
      updatedAt: new Date("2025-01-05"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      nombre: "Préstamo Personal",
      descripcion: "Préstamo para estudios",
      categoria: "Préstamo Personal",
      montoDeuda: 5000.0,
      montoPagado: 1000.0,
      tasaInteres: 12.0,
      cuotaMensual: 250.0,
      fechaPago: new Date("2026-02-15"),
      estado: "activo",
      prioridad: "normal",
      estrategia: "bola_nieve",
      acreedor: "Cooperativa 29 de Octubre",
      numeroContrato: "PRES-789456",
      icono: "🏦",
      color: "#4ECDC4",
      notificacionActiva: true,
      historialPagos: [
        { fecha: new Date("2024-10-15"), monto: 250, nota: "Primer pago" },
        { fecha: new Date("2024-11-15"), monto: 250, nota: "Segundo pago" },
        { fecha: new Date("2024-12-15"), monto: 250, nota: "Tercer pago" },
        { fecha: new Date("2025-01-15"), monto: 250, nota: "Cuarto pago" },
      ],
      createdAt: new Date("2024-10-01"),
      updatedAt: new Date("2025-01-15"),
    },
    // Planes de deuda de Carlos
    {
      perfilId: perfilIds.carlosPersonal,
      nombre: "Tarjeta American Express",
      descripcion: "Deuda de tarjeta corporativa",
      categoria: "Tarjeta de Crédito",
      montoDeuda: 25000.0,
      montoPagado: 5000.0,
      tasaInteres: 22.0,
      cuotaMensual: 2000.0,
      fechaPago: new Date("2026-02-10"),
      estado: "activo",
      prioridad: "alta",
      estrategia: "avalancha",
      acreedor: "American Express México",
      numeroContrato: "AMEX-456789",
      icono: "💳",
      color: "#1E88E5",
      notificacionActiva: true,
      historialPagos: [
        { fecha: new Date("2024-11-10"), monto: 1500, nota: "Pago inicial" },
        { fecha: new Date("2024-12-10"), monto: 2000, nota: "Pago mensual" },
        { fecha: new Date("2025-01-10"), monto: 1500, nota: "Pago mensual" },
      ],
      createdAt: new Date("2024-11-01"),
      updatedAt: new Date("2025-01-10"),
    },
    {
      perfilId: perfilIds.carlosPersonal,
      nombre: "Hipoteca",
      descripcion: "Crédito hipotecario del departamento",
      categoria: "Hipoteca",
      montoDeuda: 800000.0,
      montoPagado: 50000.0,
      tasaInteres: 9.5,
      cuotaMensual: 5000.0,
      fechaPago: new Date("2026-02-01"),
      estado: "activo",
      prioridad: "alta",
      estrategia: "equilibrada",
      acreedor: "HSBC México",
      numeroContrato: "HIP-2024-001",
      icono: "🏠",
      color: "#8BC34A",
      notificacionActiva: true,
      historialPagos: [
        { fecha: new Date("2024-04-01"), monto: 5000, nota: "Mes 1" },
        { fecha: new Date("2024-05-01"), monto: 5000, nota: "Mes 2" },
        { fecha: new Date("2024-06-01"), monto: 5000, nota: "Mes 3" },
        { fecha: new Date("2024-07-01"), monto: 5000, nota: "Mes 4" },
        { fecha: new Date("2024-08-01"), monto: 5000, nota: "Mes 5" },
        { fecha: new Date("2024-09-01"), monto: 5000, nota: "Mes 6" },
        { fecha: new Date("2024-10-01"), monto: 5000, nota: "Mes 7" },
        { fecha: new Date("2024-11-01"), monto: 5000, nota: "Mes 8" },
        { fecha: new Date("2024-12-01"), monto: 5000, nota: "Mes 9" },
        { fecha: new Date("2025-01-01"), monto: 5000, nota: "Mes 10" },
      ],
      createdAt: new Date("2024-04-01"),
      updatedAt: new Date("2025-01-01"),
    },
    {
      perfilId: perfilIds.carlosPersonal,
      nombre: "Préstamo Auto Anterior",
      descripcion: "Último pago del auto anterior",
      categoria: "Préstamo Auto",
      montoDeuda: 15000.0,
      montoPagado: 15000.0,
      tasaInteres: 11.0,
      cuotaMensual: 0,
      fechaPago: new Date("2024-12-01"),
      estado: "completado",
      prioridad: "normal",
      estrategia: "equilibrada",
      acreedor: "Banco Azteca",
      numeroContrato: "AUTO-2022-555",
      icono: "🚙",
      color: "#607D8B",
      notificacionActiva: false,
      historialPagos: [
        { fecha: new Date("2024-10-01"), monto: 5000, nota: "Penúltimo pago" },
        { fecha: new Date("2024-11-01"), monto: 5000, nota: "Último pago" },
        { fecha: new Date("2024-12-01"), monto: 5000, nota: "¡Deuda liquidada!" },
      ],
      createdAt: new Date("2022-01-01"),
      updatedAt: new Date("2024-12-01"),
    },
  ];
};

module.exports = { getPlanesDeudaSeedData };
