/**
 * Seed de Planes de Ahorro para MongoDB
 * Equivalente al seeder 20260118000006-demo-planes-ahorro.js de PostgreSQL
 */

// Esta función recibe los IDs de los perfiles creados dinámicamente
const getPlanesAhorroSeedData = (perfilIds) => {
  // perfilIds es un objeto con: { adminPerfil, mariaPersonal, mariaNegocio, carlosPersonal }
  return [
    // Planes de ahorro del perfil Personal de María
    {
      perfilId: perfilIds.mariaPersonal,
      nombre: "Vacaciones 2026",
      descripcion: "Viaje familiar a la playa en verano",
      objetivo: "Disfrutar de unas merecidas vacaciones",
      montoActual: 400.0,
      montoMeta: 2000.0,
      montoAhorrarMensual: 200.0,
      categoria: "Viajes",
      fechaInicio: new Date("2024-03-01"),
      fechaMeta: new Date("2026-08-01"),
      estado: "activo",
      prioridad: "alta",
      icono: "✈️",
      color: "#4CAF50",
      depositosRealizados: 2,
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-04-01"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      nombre: "Fondo de Emergencia",
      descripcion: "Ahorro para imprevistos",
      objetivo: "Tener un colchón financiero de 3 meses de gastos",
      montoActual: 1000.0,
      montoMeta: 4500.0,
      montoAhorrarMensual: 150.0,
      categoria: "Personal",
      fechaInicio: new Date("2024-02-15"),
      fechaMeta: new Date("2026-12-31"),
      estado: "activo",
      prioridad: "alta",
      icono: "🚨",
      color: "#FF9800",
      depositosRealizados: 7,
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-08-15"),
    },
    {
      perfilId: perfilIds.mariaPersonal,
      nombre: "Laptop Nueva",
      descripcion: "MacBook Pro para trabajo",
      objetivo: "Comprar equipo para mejorar productividad",
      montoActual: 1200.0,
      montoMeta: 1200.0,
      montoAhorrarMensual: 0,
      categoria: "Educación",
      fechaInicio: new Date("2024-01-01"),
      fechaMeta: new Date("2024-06-01"),
      estado: "completado",
      prioridad: "normal",
      icono: "💻",
      color: "#2196F3",
      depositosRealizados: 6,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-06-01"),
    },
    // Planes de ahorro de Carlos
    {
      perfilId: perfilIds.carlosPersonal,
      nombre: "Enganche de Auto",
      descripcion: "Ahorro para el enganche de un vehículo nuevo",
      objetivo: "Comprar auto en 2027",
      montoActual: 10000.0,
      montoMeta: 50000.0,
      montoAhorrarMensual: 2000.0,
      categoria: "Vehículo",
      fechaInicio: new Date("2024-03-01"),
      fechaMeta: new Date("2027-03-01"),
      estado: "activo",
      prioridad: "alta",
      icono: "🚗",
      color: "#9C27B0",
      depositosRealizados: 5,
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-08-01"),
    },
    {
      perfilId: perfilIds.carlosPersonal,
      nombre: "Maestría en Finanzas",
      descripcion: "Ahorro para estudios de posgrado",
      objetivo: "Financiar maestría en universidad privada",
      montoActual: 30000.0,
      montoMeta: 120000.0,
      montoAhorrarMensual: 3000.0,
      categoria: "Educación",
      fechaInicio: new Date("2024-01-01"),
      fechaMeta: new Date("2027-01-01"),
      estado: "activo",
      prioridad: "normal",
      icono: "🎓",
      color: "#3F51B5",
      depositosRealizados: 10,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-10-01"),
    },
  ];
};

module.exports = { getPlanesAhorroSeedData };
